<?php

namespace App\Enums;

enum ActivityEventType: string
{
    case ProductCreated = 'product_created';
    case ProductUpdated = 'product_updated';
    case ShippingOptionUpdated = 'shipping_option_updated';
    case OrderCreated = 'order_created';
    case PaymentConfirmed = 'payment_confirmed';
    case WarehouseJobCreated = 'warehouse_job_created';
    case WarehouseStatusChanged = 'warehouse_status_changed';
    case ShipmentCreated = 'shipment_created';
    case TrackingEventAdded = 'tracking_event_added';
    case NotificationTemplateUpdated = 'notification_template_updated';
    case NotificationSent = 'notification_sent';
    case AdminLogin = 'admin_login';
    case AdminLogout = 'admin_logout';
    case ReturnRequested = 'return_requested';
    case ReturnApproved = 'return_approved';
    case ReturnRejected = 'return_rejected';
    case ReturnCompleted = 'return_completed';
    case ReturnRefundAmountChanged = 'return_refund_amount_changed';
    case RefundCreated = 'refund_created';
    case RefundCompleted = 'refund_completed';
    case CommerceChannelAssigned = 'commerce_channel_assigned';
    case CommerceOrderCreated = 'commerce_order_created';
    case SupplierCreated = 'supplier_created';
    case SupplierUpdated = 'supplier_updated';
    case PurchaseOrderCreated = 'purchase_order_created';
    case PurchaseOrderConfirmed = 'purchase_order_confirmed';
    case PurchaseOrderStatusChanged = 'purchase_order_status_changed';
    case GoodsReceived = 'goods_received';
    case InventoryReceived = 'inventory_received';
    case OrderCostCaptured = 'order_cost_captured';
    case CostUpdated = 'cost_updated';
    case ProfitCalculated = 'profit_calculated';
    case CustomerProfileCreated = 'customer_profile_created';
    case CustomerProfileUpdated = 'customer_profile_updated';
    case CustomerStatusChanged = 'customer_status_changed';
    case CustomerBlocked = 'customer_blocked';
    case CustomerUnblocked = 'customer_unblocked';
    case CustomerTagAssigned = 'customer_tag_assigned';
    case CustomerTagRemoved = 'customer_tag_removed';
    case CustomerNoteAdded = 'customer_note_added';
    case CustomerNoteUpdated = 'customer_note_updated';
    case CustomerNoteDeleted = 'customer_note_deleted';
    case CustomerMetricsRebuilt = 'customer_metrics_rebuilt';
    case PromotionCreated = 'promotion_created';
    case PromotionUpdated = 'promotion_updated';
    case PromotionActivated = 'promotion_activated';
    case PromotionUsed = 'promotion_used';
    case PromotionExpired = 'promotion_expired';
    case StoreCreated = 'store_created';
    case StoreActivated = 'store_activated';
    case StoreDeactivated = 'store_deactivated';
    case CashierAssignedToStore = 'cashier_assigned_to_store';
    case CashierRemovedFromStore = 'cashier_removed_from_store';
    case PaymentMethodCreated = 'payment_method_created';
    case PaymentMethodActivated = 'payment_method_activated';
    case PaymentMethodDeactivated = 'payment_method_deactivated';
    case PosSessionOpened = 'pos_session_opened';
    case PosSessionClosed = 'pos_session_closed';
    case PosSaleCompleted = 'pos_sale_completed';
    case PosVarianceDetected = 'pos_variance_detected';
    case PosFloatUpdated = 'pos_float_updated';
    case PosReceiptGenerated = 'pos_receipt_generated';
    case PosReceiptPrinted = 'pos_receipt_printed';
    case PosReceiptReprinted = 'pos_receipt_reprinted';
    case PosReturnStarted = 'pos_return_started';
    case PosReturnCompleted = 'pos_return_completed';
    case PosRefundIssued = 'pos_refund_issued';
    case PosExchangeCompleted = 'pos_exchange_completed';
    case PosInventoryReturned = 'pos_inventory_returned';
    case PosInventoryMarkedDamaged = 'pos_inventory_marked_damaged';
    case AnalyticsReportExported = 'analytics_report_exported';
    case LoyaltyAccountEnrolled = 'loyalty_account_enrolled';
    case LoyaltyPointsEarned = 'loyalty_points_earned';
    case LoyaltyPointsRedeemed = 'loyalty_points_redeemed';
    case LoyaltyPointsAdjusted = 'loyalty_points_adjusted';
    case LoyaltyTierChanged = 'loyalty_tier_changed';
    case LoyaltyRewardIssued = 'loyalty_reward_issued';
    case InventoryAdjusted = 'inventory_adjusted';
    case StockCountCompleted = 'stock_count_completed';
    case DamagedStockRecorded = 'damaged_stock_recorded';
    case GrowthSegmentCreated = 'growth_segment_created';
    case GrowthCampaignCreated = 'growth_campaign_created';
    case GrowthCampaignUpdated = 'growth_campaign_updated';
    case GrowthCampaignSent = 'growth_campaign_sent';
    case GrowthJourneyCreated = 'growth_journey_created';
    case CmsHomepageLayoutCreated = 'cms_homepage_layout_created';
    case CmsHomepageLayoutUpdated = 'cms_homepage_layout_updated';
    case CmsHomepageLayoutSetDefault = 'cms_homepage_layout_set_default';
    case CmsHomepageLayoutActivated = 'cms_homepage_layout_activated';
    case CmsHomepageLayoutArchived = 'cms_homepage_layout_archived';
    case CmsHomepageSectionCreated = 'cms_homepage_section_created';
    case CmsHomepageSectionUpdated = 'cms_homepage_section_updated';
    case CmsHomepageSectionVisibilityChanged = 'cms_homepage_section_visibility_changed';
    case CmsHomepageSectionsReordered = 'cms_homepage_sections_reordered';
    case CmsHomepageSectionDeleted = 'cms_homepage_section_deleted';
    case CmsHeroSlideCreated = 'cms_hero_slide_created';
    case CmsHeroSlideUpdated = 'cms_hero_slide_updated';
    case CmsHeroSlideActivated = 'cms_hero_slide_activated';
    case CmsHeroSlideArchived = 'cms_hero_slide_archived';
    case CmsHeroSlideVisibilityChanged = 'cms_hero_slide_visibility_changed';
    case CmsHeroSlidesReordered = 'cms_hero_slides_reordered';
    case CmsHeroSlideDeleted = 'cms_hero_slide_deleted';
    case CmsFeaturedContentCreated = 'cms_featured_content_created';
    case CmsFeaturedContentUpdated = 'cms_featured_content_updated';
    case CmsFeaturedContentVisibilityChanged = 'cms_featured_content_visibility_changed';
    case CmsFeaturedContentsReordered = 'cms_featured_contents_reordered';
    case CmsFeaturedContentDeleted = 'cms_featured_content_deleted';
    case CmsCampaignCreated = 'cms_campaign_created';
    case CmsCampaignUpdated = 'cms_campaign_updated';
    case CmsCampaignActivated = 'cms_campaign_activated';
    case CmsCampaignArchived = 'cms_campaign_archived';
    case CmsCampaignScheduleChanged = 'cms_campaign_schedule_changed';
    case CmsCampaignPriorityChanged = 'cms_campaign_priority_changed';
    case CmsNavigationShellCreated = 'cms_navigation_shell_created';
    case CmsNavigationShellUpdated = 'cms_navigation_shell_updated';
    case CmsNavigationShellPublished = 'cms_navigation_shell_published';
    case CmsNavigationShellDeleted = 'cms_navigation_shell_deleted';
    case CmsNavigationItemCreated = 'cms_navigation_item_created';
    case CmsNavigationItemUpdated = 'cms_navigation_item_updated';
    case CmsNavigationItemEnabled = 'cms_navigation_item_enabled';
    case CmsNavigationItemDisabled = 'cms_navigation_item_disabled';
    case CmsNavigationItemDeleted = 'cms_navigation_item_deleted';
    case CmsNavigationItemsReordered = 'cms_navigation_items_reordered';

    public function label(): string
    {
        return match ($this) {
            self::ProductCreated => 'Product Created',
            self::ProductUpdated => 'Product Updated',
            self::ShippingOptionUpdated => 'Shipping Option Updated',
            self::OrderCreated => 'Order Created',
            self::PaymentConfirmed => 'Payment Confirmed',
            self::WarehouseJobCreated => 'Warehouse Job Created',
            self::WarehouseStatusChanged => 'Warehouse Status Changed',
            self::ShipmentCreated => 'Shipment Created',
            self::TrackingEventAdded => 'Tracking Event Added',
            self::NotificationTemplateUpdated => 'Notification Template Updated',
            self::NotificationSent => 'Notification Sent',
            self::AdminLogin => 'Admin Login',
            self::AdminLogout => 'Admin Logout',
            self::ReturnRequested => 'Return Requested',
            self::ReturnApproved => 'Return Approved',
            self::ReturnRejected => 'Return Rejected',
            self::ReturnCompleted => 'Return Completed',
            self::ReturnRefundAmountChanged => 'Return Refund Amount Changed',
            self::RefundCreated => 'Refund Created',
            self::RefundCompleted => 'Refund Completed',
            self::CommerceChannelAssigned => 'Commerce Channel Assigned',
            self::CommerceOrderCreated => 'Commerce Order Created',
            self::SupplierCreated => 'Supplier Created',
            self::SupplierUpdated => 'Supplier Updated',
            self::PurchaseOrderCreated => 'Purchase Order Created',
            self::PurchaseOrderConfirmed => 'Purchase Order Confirmed',
            self::PurchaseOrderStatusChanged => 'Purchase Order Status Changed',
            self::GoodsReceived => 'Goods Received',
            self::InventoryReceived => 'Inventory Received',
            self::OrderCostCaptured => 'Order Cost Captured',
            self::CostUpdated => 'Cost Updated',
            self::ProfitCalculated => 'Profit Calculated',
            self::CustomerProfileCreated => 'Customer Profile Created',
            self::CustomerProfileUpdated => 'Customer Profile Updated',
            self::CustomerStatusChanged => 'Customer Status Changed',
            self::CustomerBlocked => 'Customer Blocked',
            self::CustomerUnblocked => 'Customer Unblocked',
            self::CustomerTagAssigned => 'Customer Tag Assigned',
            self::CustomerTagRemoved => 'Customer Tag Removed',
            self::CustomerNoteAdded => 'Customer Note Added',
            self::CustomerNoteUpdated => 'Customer Note Updated',
            self::CustomerNoteDeleted => 'Customer Note Deleted',
            self::CustomerMetricsRebuilt => 'Customer Metrics Rebuilt',
            self::PromotionCreated => 'Promotion Created',
            self::PromotionUpdated => 'Promotion Updated',
            self::PromotionActivated => 'Promotion Activated',
            self::PromotionUsed => 'Promotion Used',
            self::PromotionExpired => 'Promotion Expired',
            self::StoreCreated => 'Store Created',
            self::StoreActivated => 'Store Activated',
            self::StoreDeactivated => 'Store Deactivated',
            self::CashierAssignedToStore => 'Cashier Assigned To Store',
            self::CashierRemovedFromStore => 'Cashier Removed From Store',
            self::PaymentMethodCreated => 'Payment Method Created',
            self::PaymentMethodActivated => 'Payment Method Activated',
            self::PaymentMethodDeactivated => 'Payment Method Deactivated',
            self::PosSessionOpened => 'POS Session Opened',
            self::PosSessionClosed => 'POS Session Closed',
            self::PosSaleCompleted => 'POS Sale Completed',
            self::PosVarianceDetected => 'POS Variance Detected',
            self::PosFloatUpdated => 'POS Float Updated',
            self::PosReceiptGenerated => 'POS Receipt Generated',
            self::PosReceiptPrinted => 'POS Receipt Printed',
            self::PosReceiptReprinted => 'POS Receipt Reprinted',
            self::PosReturnStarted => 'POS Return Started',
            self::PosReturnCompleted => 'POS Return Completed',
            self::PosRefundIssued => 'POS Refund Issued',
            self::PosExchangeCompleted => 'POS Exchange Completed',
            self::PosInventoryReturned => 'POS Inventory Returned',
            self::PosInventoryMarkedDamaged => 'POS Inventory Marked Damaged',
            self::AnalyticsReportExported => 'Analytics Report Exported',
            self::LoyaltyAccountEnrolled => 'Loyalty Account Enrolled',
            self::LoyaltyPointsEarned => 'Loyalty Points Earned',
            self::LoyaltyPointsRedeemed => 'Loyalty Points Redeemed',
            self::LoyaltyPointsAdjusted => 'Loyalty Points Adjusted',
            self::LoyaltyTierChanged => 'Loyalty Tier Changed',
            self::LoyaltyRewardIssued => 'Loyalty Reward Issued',
            self::InventoryAdjusted => 'Inventory Adjusted',
            self::StockCountCompleted => 'Stock Count Completed',
            self::DamagedStockRecorded => 'Damaged Stock Recorded',
            self::GrowthSegmentCreated => 'Growth Segment Created',
            self::GrowthCampaignCreated => 'Growth Campaign Created',
            self::GrowthCampaignUpdated => 'Growth Campaign Updated',
            self::GrowthCampaignSent => 'Growth Campaign Sent',
            self::GrowthJourneyCreated => 'Growth Journey Created',
            self::CmsHomepageLayoutCreated => 'CMS Homepage Layout Created',
            self::CmsHomepageLayoutUpdated => 'CMS Homepage Layout Updated',
            self::CmsHomepageLayoutSetDefault => 'CMS Homepage Layout Set Default',
            self::CmsHomepageLayoutActivated => 'CMS Homepage Layout Activated',
            self::CmsHomepageLayoutArchived => 'CMS Homepage Layout Archived',
            self::CmsHomepageSectionCreated => 'CMS Homepage Section Created',
            self::CmsHomepageSectionUpdated => 'CMS Homepage Section Updated',
            self::CmsHomepageSectionVisibilityChanged => 'CMS Homepage Section Visibility Changed',
            self::CmsHomepageSectionsReordered => 'CMS Homepage Sections Reordered',
            self::CmsHomepageSectionDeleted => 'CMS Homepage Section Deleted',
            self::CmsHeroSlideCreated => 'CMS Hero Slide Created',
            self::CmsHeroSlideUpdated => 'CMS Hero Slide Updated',
            self::CmsHeroSlideActivated => 'CMS Hero Slide Activated',
            self::CmsHeroSlideArchived => 'CMS Hero Slide Archived',
            self::CmsHeroSlideVisibilityChanged => 'CMS Hero Slide Visibility Changed',
            self::CmsHeroSlidesReordered => 'CMS Hero Slides Reordered',
            self::CmsHeroSlideDeleted => 'CMS Hero Slide Deleted',
            self::CmsFeaturedContentCreated => 'CMS Featured Content Created',
            self::CmsFeaturedContentUpdated => 'CMS Featured Content Updated',
            self::CmsFeaturedContentVisibilityChanged => 'CMS Featured Content Visibility Changed',
            self::CmsFeaturedContentsReordered => 'CMS Featured Contents Reordered',
            self::CmsFeaturedContentDeleted => 'CMS Featured Content Deleted',
            self::CmsCampaignCreated => 'CMS Campaign Created',
            self::CmsCampaignUpdated => 'CMS Campaign Updated',
            self::CmsCampaignActivated => 'CMS Campaign Activated',
            self::CmsCampaignArchived => 'CMS Campaign Archived',
            self::CmsCampaignScheduleChanged => 'CMS Campaign Schedule Changed',
            self::CmsCampaignPriorityChanged => 'CMS Campaign Priority Changed',
            self::CmsNavigationShellCreated => 'CMS Navigation Shell Created',
            self::CmsNavigationShellUpdated => 'CMS Navigation Shell Updated',
            self::CmsNavigationShellPublished => 'CMS Navigation Shell Published',
            self::CmsNavigationShellDeleted => 'CMS Navigation Shell Deleted',
            self::CmsNavigationItemCreated => 'CMS Navigation Item Created',
            self::CmsNavigationItemUpdated => 'CMS Navigation Item Updated',
            self::CmsNavigationItemEnabled => 'CMS Navigation Item Enabled',
            self::CmsNavigationItemDisabled => 'CMS Navigation Item Disabled',
            self::CmsNavigationItemDeleted => 'CMS Navigation Item Deleted',
            self::CmsNavigationItemsReordered => 'CMS Navigation Items Reordered',
        };
    }

    public function defaultAction(): string
    {
        return match ($this) {
            self::ProductCreated => 'created',
            self::ProductUpdated => 'updated',
            self::ShippingOptionUpdated => 'updated',
            self::OrderCreated => 'created',
            self::PaymentConfirmed => 'confirmed',
            self::WarehouseJobCreated => 'created',
            self::WarehouseStatusChanged => 'status_changed',
            self::ShipmentCreated => 'created',
            self::TrackingEventAdded => 'added',
            self::NotificationTemplateUpdated => 'updated',
            self::NotificationSent => 'sent',
            self::AdminLogin => 'login',
            self::AdminLogout => 'logout',
            self::ReturnRequested => 'requested',
            self::ReturnApproved => 'approved',
            self::ReturnRejected => 'rejected',
            self::ReturnCompleted => 'completed',
            self::ReturnRefundAmountChanged => 'amount_changed',
            self::RefundCreated => 'created',
            self::RefundCompleted => 'completed',
            self::CommerceChannelAssigned => 'assigned',
            self::CommerceOrderCreated => 'created',
            self::SupplierCreated => 'created',
            self::SupplierUpdated => 'updated',
            self::PurchaseOrderCreated => 'created',
            self::PurchaseOrderConfirmed => 'confirmed',
            self::PurchaseOrderStatusChanged => 'status_changed',
            self::GoodsReceived => 'received',
            self::InventoryReceived => 'received',
            self::OrderCostCaptured => 'captured',
            self::CostUpdated => 'updated',
            self::ProfitCalculated => 'calculated',
            self::CustomerProfileCreated => 'created',
            self::CustomerProfileUpdated => 'updated',
            self::CustomerStatusChanged => 'status_changed',
            self::CustomerBlocked => 'blocked',
            self::CustomerUnblocked => 'unblocked',
            self::CustomerTagAssigned => 'assigned',
            self::CustomerTagRemoved => 'removed',
            self::CustomerNoteAdded => 'added',
            self::CustomerNoteUpdated => 'updated',
            self::CustomerNoteDeleted => 'deleted',
            self::CustomerMetricsRebuilt => 'rebuilt',
            self::PromotionCreated => 'created',
            self::PromotionUpdated => 'updated',
            self::PromotionActivated => 'activated',
            self::PromotionUsed => 'used',
            self::PromotionExpired => 'expired',
            self::StoreCreated => 'created',
            self::StoreActivated => 'activated',
            self::StoreDeactivated => 'deactivated',
            self::CashierAssignedToStore => 'assigned',
            self::CashierRemovedFromStore => 'removed',
            self::PaymentMethodCreated => 'created',
            self::PaymentMethodActivated => 'activated',
            self::PaymentMethodDeactivated => 'deactivated',
            self::PosSessionOpened => 'opened',
            self::PosSessionClosed => 'closed',
            self::PosSaleCompleted => 'completed',
            self::PosVarianceDetected => 'variance_detected',
            self::PosFloatUpdated => 'float_updated',
            self::PosReceiptGenerated => 'generated',
            self::PosReceiptPrinted => 'printed',
            self::PosReceiptReprinted => 'reprinted',
            self::PosReturnStarted => 'started',
            self::PosReturnCompleted => 'completed',
            self::PosRefundIssued => 'issued',
            self::PosExchangeCompleted => 'completed',
            self::PosInventoryReturned => 'returned',
            self::PosInventoryMarkedDamaged => 'marked_damaged',
            self::AnalyticsReportExported => 'exported',
            self::LoyaltyAccountEnrolled => 'enrolled',
            self::LoyaltyPointsEarned => 'earned',
            self::LoyaltyPointsRedeemed => 'redeemed',
            self::LoyaltyPointsAdjusted => 'adjusted',
            self::LoyaltyTierChanged => 'tier_changed',
            self::LoyaltyRewardIssued => 'issued',
            self::InventoryAdjusted => 'adjusted',
            self::StockCountCompleted => 'completed',
            self::DamagedStockRecorded => 'recorded',
            self::GrowthSegmentCreated => 'created',
            self::GrowthCampaignCreated => 'created',
            self::GrowthCampaignUpdated => 'updated',
            self::GrowthCampaignSent => 'sent',
            self::GrowthJourneyCreated => 'created',
            self::CmsHomepageLayoutCreated => 'created',
            self::CmsHomepageLayoutUpdated => 'updated',
            self::CmsHomepageLayoutSetDefault => 'set_default',
            self::CmsHomepageLayoutActivated => 'activated',
            self::CmsHomepageLayoutArchived => 'archived',
            self::CmsHomepageSectionCreated => 'created',
            self::CmsHomepageSectionUpdated => 'updated',
            self::CmsHomepageSectionVisibilityChanged => 'visibility_changed',
            self::CmsHomepageSectionsReordered => 'reordered',
            self::CmsHomepageSectionDeleted => 'deleted',
            self::CmsHeroSlideCreated => 'created',
            self::CmsHeroSlideUpdated => 'updated',
            self::CmsHeroSlideActivated => 'activated',
            self::CmsHeroSlideArchived => 'archived',
            self::CmsHeroSlideVisibilityChanged => 'visibility_changed',
            self::CmsHeroSlidesReordered => 'reordered',
            self::CmsHeroSlideDeleted => 'deleted',
            self::CmsFeaturedContentCreated => 'created',
            self::CmsFeaturedContentUpdated => 'updated',
            self::CmsFeaturedContentVisibilityChanged => 'visibility_changed',
            self::CmsFeaturedContentsReordered => 'reordered',
            self::CmsFeaturedContentDeleted => 'deleted',
            self::CmsCampaignCreated => 'created',
            self::CmsCampaignUpdated => 'updated',
            self::CmsCampaignActivated => 'activated',
            self::CmsCampaignArchived => 'archived',
            self::CmsCampaignScheduleChanged => 'schedule_changed',
            self::CmsCampaignPriorityChanged => 'priority_changed',
            self::CmsNavigationShellCreated => 'created',
            self::CmsNavigationShellUpdated => 'updated',
            self::CmsNavigationShellPublished => 'published',
            self::CmsNavigationShellDeleted => 'deleted',
            self::CmsNavigationItemCreated => 'created',
            self::CmsNavigationItemUpdated => 'updated',
            self::CmsNavigationItemEnabled => 'enabled',
            self::CmsNavigationItemDisabled => 'disabled',
            self::CmsNavigationItemDeleted => 'deleted',
            self::CmsNavigationItemsReordered => 'reordered',
        };
    }
}
