import type { BrandCategory } from "@/lib/catalog/brands";

function cat(name: string, slug: string): BrandCategory {
  return { name, slug };
}

export const ZION_MODE_SUBCATEGORIES: readonly BrandCategory[] = [
  cat("Dresses", "dresses"),
  cat("Bodycon Dresses", "bodycon-dresses"),
  cat("Pencil Dresses", "pencil-dresses"),
  cat("Maxi Dresses", "maxi-dresses"),
  cat("Mini Dresses", "mini-dresses"),
  cat("Blouses", "blouses"),
  cat("Tops", "tops"),
  cat("T-Shirts", "t-shirts"),
  cat("Jeans", "jeans"),
  cat("Trousers", "trousers"),
  cat("Skirts", "skirts"),
  cat("Jackets", "jackets"),
  cat("Coats", "coats"),
  cat("Hoodies", "hoodies"),
  cat("Sweaters", "sweaters"),
  cat("Two Piece Sets", "two-piece-sets"),
  cat("Activewear", "activewear"),
  cat("Leggings", "leggings"),
  cat("Jumpsuits", "jumpsuits"),
  cat("Handbags", "handbags"),
  cat("High Heels", "high-heels"),
  cat("Sneakers", "sneakers"),
  cat("Sandals", "sandals"),
  cat("Watches", "watches"),
  cat("Sunglasses", "sunglasses"),
  cat("Accessories", "accessories"),
];

export const PEACHY_LINGERIE_SUBCATEGORIES: readonly BrandCategory[] = [
  cat("Bras", "bras"),
  cat("Panties", "panties"),
  cat("Underwear Sets", "underwear-sets"),
  cat("Lingerie Sets", "lingerie-sets"),
  cat("Bodysuits", "bodysuits"),
  cat("Teddies", "teddies"),
  cat("Babydolls", "babydolls"),
  cat("Chemises", "chemises"),
  cat("Robes", "robes"),
  cat("Sleepwear", "sleepwear"),
  cat("Nightgowns", "nightgowns"),
  cat("Shapewear", "shapewear"),
  cat("Corsets", "corsets"),
  cat("Bustiers", "bustiers"),
  cat("Stockings", "stockings"),
  cat("Tights", "tights"),
  cat("Garter Belts", "garter-belts"),
  cat("Bridal Lingerie", "bridal-lingerie"),
  cat("Plus Size Lingerie", "plus-size-lingerie"),
  cat("Lounge Sets", "lounge-sets"),
];

export const TZUR_JEWELRY_SUBCATEGORIES: readonly BrandCategory[] = [
  cat("Necklaces", "necklaces"),
  cat("Chains", "chains"),
  cat("Pendants", "pendants"),
  cat("Chokers", "chokers"),
  cat("Rings", "rings"),
  cat("Engagement Rings", "engagement-rings"),
  cat("Wedding Bands", "wedding-bands"),
  cat("Earrings", "earrings"),
  cat("Stud Earrings", "stud-earrings"),
  cat("Hoop Earrings", "hoop-earrings"),
  cat("Bracelets", "bracelets"),
  cat("Bangles", "bangles"),
  cat("Anklets", "anklets"),
  cat("Brooches", "brooches"),
  cat("Jewelry Sets", "jewelry-sets"),
  cat("Watches", "watches"),
  cat("Men's Jewelry", "mens-jewelry"),
  cat("Women's Jewelry", "womens-jewelry"),
  cat("Gold Plated", "gold-plated"),
  cat("Sterling Silver", "sterling-silver"),
  cat("Pearl Jewelry", "pearl-jewelry"),
  cat("Gift Collection", "gift-collection"),
  cat("Custom Jewelry", "custom-jewelry"),
];

export const ROVI_BEAUTY_STORE_SUBCATEGORIES: readonly BrandCategory[] = [
  cat("Human Hair Wigs", "human-hair-wigs"),
  cat("Synthetic Wigs", "synthetic-wigs"),
  cat("Hair Extensions", "hair-extensions"),
  cat("Lace Front Wigs", "lace-front-wigs"),
  cat("Hair Bundles", "hair-bundles"),
  cat("Closures", "closures"),
  cat("Frontals", "frontals"),
  cat("Makeup", "makeup"),
  cat("Foundation", "foundation"),
  cat("Lipstick", "lipstick"),
  cat("Lip Gloss", "lip-gloss"),
  cat("Mascara", "mascara"),
  cat("Eyelashes", "eyelashes"),
  cat("Face Powder", "face-powder"),
  cat("Perfumes", "perfumes"),
  cat("Body Sprays", "body-sprays"),
  cat("Skin Care", "skin-care"),
  cat("Face Wash", "face-wash"),
  cat("Facial Serum", "facial-serum"),
  cat("Moisturizers", "moisturizers"),
  cat("Body Lotion", "body-lotion"),
  cat("Body Oil", "body-oil"),
  cat("Soap", "soap"),
  cat("Sunscreen", "sunscreen"),
  cat("Nail Polish", "nail-polish"),
  cat("Beauty Accessories", "beauty-accessories"),
];
