/** Static ecommerce taxonomy for All Categories mega menu (future API-compatible slugs). */

export const CATEGORY_SUBCATEGORY_NAMES: Record<string, readonly string[]> = {
  electronics: [
    "Smartphones",
    "Feature Phones",
    "Tablets",
    "Laptops",
    "Desktop PCs",
    "Monitors",
    "TVs",
    "Smart Watches",
    "Headphones",
    "Earbuds",
    "Speakers",
    "Cameras",
    "Drones",
    "Gaming Consoles",
    "Accessories",
    "Chargers",
    "Power Banks",
    "Storage Devices",
    "Networking",
    "Printers",
  ],
  "womens-fashion": [
    "Dresses",
    "Bodycon Dresses",
    "Pencil Dresses",
    "Maxi Dresses",
    "Mini Dresses",
    "Blouses",
    "Tops",
    "Jeans",
    "Skirts",
    "Handbags",
    "High Heels",
    "Sneakers",
    "Sandals",
    "Activewear",
    "Jackets",
    "Hoodies",
    "Sweaters",
    "Accessories",
    "T-Shirts",
    "Trousers",
    "Two Piece Sets",
    "Coats",
    "Leggings",
    "Jumpsuits",
    "Watches",
    "Sunglasses",
  ],
  "mens-fashion": [
    "Shirts",
    "T-Shirts",
    "Polo Shirts",
    "Suits",
    "Blazers",
    "Pants",
    "Jeans",
    "Shorts",
    "Sneakers",
    "Formal Shoes",
    "Boots",
    "Sandals",
    "Watches",
    "Belts",
    "Wallets",
    "Bags",
    "Sportswear",
    "Hoodies",
    "Jackets",
    "Sweaters",
    "Underwear",
    "Accessories",
    "Ties",
    "Cufflinks",
  ],
  beauty: [
    "Skincare",
    "Face Wash",
    "Facial Serum",
    "Moisturizers",
    "Sunscreen",
    "Makeup",
    "Foundation",
    "Lipstick",
    "Lip Gloss",
    "Mascara",
    "Eyelashes",
    "Face Powder",
    "Perfumes",
    "Body Sprays",
    "Hair Care",
    "Shampoo",
    "Conditioner",
    "Hair Oil",
    "Nail Polish",
    "Beauty Tools",
    "Body Lotion",
    "Soap",
    "Fragrances",
    "Wellness",
  ],
  furniture: [
    "Sofas",
    "Sectionals",
    "Recliners",
    "Coffee Tables",
    "TV Stands",
    "Beds",
    "Mattresses",
    "Wardrobes",
    "Dressers",
    "Nightstands",
    "Dining Tables",
    "Dining Chairs",
    "Office Desks",
    "Office Chairs",
    "Bookshelves",
    "Outdoor Furniture",
    "Patio Sets",
    "Storage Cabinets",
    "Lighting",
    "Rugs",
  ],
  "building-materials": [
    "Tiles",
    "Ceramic Tiles",
    "Porcelain Tiles",
    "Doors",
    "Windows",
    "Plumbing",
    "Pipes & Fittings",
    "Electrical",
    "Wiring & Cables",
    "Switches & Sockets",
    "Paint",
    "Wall Putty",
    "Cement",
    "Steel Bars",
    "Roofing",
    "Insulation",
    "Hardware",
    "Tools",
    "Adhesives",
    "Safety Equipment",
  ],
  "home-kitchen": [
    "Cookware",
    "Pots & Pans",
    "Bakeware",
    "Knives",
    "Small Appliances",
    "Blenders",
    "Microwaves",
    "Air Fryers",
    "Bedding",
    "Sheets",
    "Pillows",
    "Comforters",
    "Decor",
    "Curtains",
    "Wall Art",
    "Storage",
    "Food Containers",
    "Tableware",
    "Dinner Sets",
    "Glassware",
    "Kitchen Organizers",
    "Cleaning Supplies",
  ],
  "kids-baby": [
    "Baby Clothing",
    "Kids Clothing",
    "School Uniforms",
    "Shoes",
    "Toys",
    "Educational Toys",
    "Strollers",
    "Car Seats",
    "Feeding",
    "Bottles",
    "High Chairs",
    "Nursery",
    "Cribs",
    "Baby Monitors",
    "Diapers",
    "School Supplies",
    "Backpacks",
    "Sports & Outdoor",
    "Party Supplies",
    "Baby Care",
  ],
};

export function getExpandedSubcategoryNames(parentSlug: string): readonly string[] {
  return CATEGORY_SUBCATEGORY_NAMES[parentSlug] ?? [];
}

export function slugifySubcategoryName(name: string): string {
  return name
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/** Future-compatible slug prefix per mega-menu parent (matches Laravel seeder patterns). */
export const CATEGORY_SUBCATEGORY_SLUG_PREFIX: Record<string, string> = {
  electronics: "electronics",
  "womens-fashion": "fashion-women",
  "mens-fashion": "fashion-men",
  "kids-baby": "fashion-kids",
  beauty: "beauty",
  furniture: "home-living-furniture",
  "home-kitchen": "home-living",
  "building-materials": "building-materials",
};

export function buildStaticSubcategorySlug(parentSlug: string, name: string): string {
  const prefix = CATEGORY_SUBCATEGORY_SLUG_PREFIX[parentSlug] ?? parentSlug;
  return `${prefix}-${slugifySubcategoryName(name)}`;
}
