import type { HomepageContent } from "./types";

const FAR_FUTURE = "2099-12-31T23:59:59.000Z";
const FAR_PAST = "2020-01-01T00:00:00.000Z";

/** Seed commercial homepage content — replace via CMS without changing section components. */
export const homepageContentSeed: HomepageContent = {
  heroSlides: [
    {
      id: "hero-china",
      type: "china",
      title: "Order from China",
      subtitle: "China Campaign",
      description: "Import carefully selected products directly from China.",
      ctaLabel: "Explore China Catalog",
      ctaHref: "/products?origin=china",
      secondaryCtaLabel: "How it works",
      secondaryCtaHref: "/#why-choose-us",
      backgroundClass:
        "bg-gradient-to-br from-zinc-950 via-zinc-900 to-[#3a1510]",
      accent: "china",
      displayStart: FAR_PAST,
      displayEnd: FAR_FUTURE,
      priority: 100,
      status: "active",
    },
    {
      id: "hero-tz",
      type: "tz",
      title: "Buy from TZ",
      subtitle: "Local Stores",
      description: "Shop trusted Tanzanian stores with local delivery.",
      ctaLabel: "Explore TZ Stores",
      ctaHref: "/buy-from-tz",
      backgroundClass:
        "bg-gradient-to-br from-zinc-950 via-zinc-900 to-[#0d2a1a]",
      accent: "tz",
      displayStart: FAR_PAST,
      displayEnd: FAR_FUTURE,
      priority: 90,
      status: "active",
    },
    {
      id: "hero-sponsor-nmb",
      type: "sponsor",
      title: "Pay with NMB",
      subtitle: "Trusted Partner",
      description: "Secure checkout with leading Tanzanian banking partners.",
      ctaLabel: "Learn More",
      ctaHref: "/#sponsors",
      sponsorName: "NMB",
      backgroundClass:
        "bg-gradient-to-br from-[#0b1f3a] via-zinc-900 to-zinc-950",
      accent: "sponsor",
      displayStart: FAR_PAST,
      displayEnd: FAR_FUTURE,
      priority: 80,
      status: "active",
    },
    {
      id: "hero-seasonal",
      type: "seasonal",
      title: "Seasonal Offers",
      subtitle: "Limited Time",
      description: "Discover rotating campaigns — Back to School, Ramadhan, Black Friday, and more.",
      ctaLabel: "Shop Deals",
      ctaHref: "/products",
      backgroundClass:
        "bg-gradient-to-br from-[#2a2110] via-zinc-900 to-zinc-950",
      accent: "gold",
      displayStart: FAR_PAST,
      displayEnd: FAR_FUTURE,
      priority: 70,
      status: "active",
    },
  ],
  advertisements: [
    {
      id: "banner-mid-visa",
      title: "Shop with Visa",
      subtitle: "Secure Payments",
      description: "Checkout confidently with Visa on CHINA ORDER TZ.",
      ctaLabel: "Visit Sponsor",
      targetUrl: "/#sponsors",
      placement: "mid_page",
      advertisementType: "sponsor",
      sponsorName: "Visa",
      backgroundClass: "bg-gradient-to-r from-[#1a1f71] to-[#0d47a1]",
      displayStart: FAR_PAST,
      displayEnd: FAR_FUTURE,
      priority: 50,
      status: "active",
    },
    {
      id: "banner-homepage-seasonal",
      title: "Flash promotions live",
      subtitle: "Homepage Banner",
      description: "Limited-time prices across China imports and TZ stores.",
      ctaLabel: "View Flash Deals",
      targetUrl: "/#flash-deals",
      placement: "homepage_banner",
      advertisementType: "seasonal",
      backgroundClass: "bg-gradient-to-r from-[#c9a227] to-[#8b6914]",
      displayStart: FAR_PAST,
      displayEnd: FAR_FUTURE,
      priority: 40,
      status: "active",
    },
    {
      id: "banner-footer-vodacom",
      title: "Stay connected with Vodacom",
      subtitle: "Partner Offer",
      description: "Trusted telecom partner supporting shoppers across Tanzania.",
      ctaLabel: "Learn More",
      targetUrl: "/#sponsors",
      placement: "footer",
      advertisementType: "sponsor",
      sponsorName: "Vodacom",
      backgroundClass: "bg-gradient-to-r from-[#e60000] to-[#8b0000]",
      displayStart: FAR_PAST,
      displayEnd: FAR_FUTURE,
      priority: 30,
      status: "active",
    },
    {
      id: "banner-footer-azam",
      title: "Azam — Trusted Partner",
      subtitle: "Sponsor",
      description: "Proud partner of CHINA ORDER TZ shoppers.",
      ctaLabel: "Visit Sponsor",
      targetUrl: "/#sponsors",
      placement: "footer",
      advertisementType: "sponsor",
      sponsorName: "Azam",
      backgroundClass: "bg-gradient-to-r from-zinc-800 to-zinc-900",
      displayStart: FAR_PAST,
      displayEnd: FAR_FUTURE,
      priority: 20,
      status: "active",
    },
  ],
  sponsors: [
    { id: "sp-nmb", name: "NMB", logoText: "NMB", href: "/#sponsors", priority: 100, status: "active", displayStart: FAR_PAST, displayEnd: FAR_FUTURE },
    { id: "sp-crdb", name: "CRDB", logoText: "CRDB", href: "/#sponsors", priority: 95, status: "active", displayStart: FAR_PAST, displayEnd: FAR_FUTURE },
    { id: "sp-nbc", name: "NBC", logoText: "NBC", href: "/#sponsors", priority: 90, status: "active", displayStart: FAR_PAST, displayEnd: FAR_FUTURE },
    { id: "sp-visa", name: "Visa", logoText: "VISA", href: "/#sponsors", priority: 85, status: "active", displayStart: FAR_PAST, displayEnd: FAR_FUTURE },
    { id: "sp-mc", name: "Mastercard", logoText: "MC", href: "/#sponsors", priority: 80, status: "active", displayStart: FAR_PAST, displayEnd: FAR_FUTURE },
    { id: "sp-azam", name: "Azam", logoText: "AZAM", href: "/#sponsors", priority: 75, status: "active", displayStart: FAR_PAST, displayEnd: FAR_FUTURE },
    { id: "sp-vodacom", name: "Vodacom", logoText: "Voda", href: "/#sponsors", priority: 70, status: "active", displayStart: FAR_PAST, displayEnd: FAR_FUTURE },
    { id: "sp-halotel", name: "Halotel", logoText: "Halo", href: "/#sponsors", priority: 65, status: "active", displayStart: FAR_PAST, displayEnd: FAR_FUTURE },
    { id: "sp-airtel", name: "Airtel", logoText: "Airtel", href: "/#sponsors", priority: 60, status: "active", displayStart: FAR_PAST, displayEnd: FAR_FUTURE },
  ],
  flashDeals: [
    {
      id: "deal-1",
      title: "Wireless earbuds bundle",
      imageEmoji: "🎧",
      oldPrice: 189000,
      newPrice: 129000,
      href: "/products?origin=china&search=earbuds",
      endsAt: new Date(Date.now() + 1000 * 60 * 60 * 36).toISOString(),
      displayStart: FAR_PAST,
      displayEnd: FAR_FUTURE,
      origin: "china",
      status: "active",
      priority: 100,
    },
    {
      id: "deal-2",
      title: "Kitchen essentials set",
      imageEmoji: "🍳",
      oldPrice: 95000,
      newPrice: 69000,
      href: "/products?search=kitchen",
      endsAt: new Date(Date.now() + 1000 * 60 * 60 * 20).toISOString(),
      displayStart: FAR_PAST,
      displayEnd: FAR_FUTURE,
      origin: "china",
      status: "active",
      priority: 90,
    },
    {
      id: "deal-3",
      title: "Beauty starter kit",
      imageEmoji: "✨",
      oldPrice: 78000,
      newPrice: 54000,
      href: "/buy-from-tz",
      endsAt: new Date(Date.now() + 1000 * 60 * 60 * 48).toISOString(),
      displayStart: FAR_PAST,
      displayEnd: FAR_FUTURE,
      origin: "tz",
      status: "active",
      priority: 80,
    },
    {
      id: "deal-4",
      title: "Office desk lamp",
      imageEmoji: "💡",
      oldPrice: 62000,
      newPrice: 41900,
      href: "/products?origin=china&search=lamp",
      endsAt: new Date(Date.now() + 1000 * 60 * 60 * 12).toISOString(),
      displayStart: FAR_PAST,
      displayEnd: FAR_FUTURE,
      origin: "china",
      status: "active",
      priority: 70,
    },
  ],
  collections: [
    {
      id: "col-electronics",
      name: "Electronics",
      slug: "electronics",
      description: "Phones, audio, and gadgets",
      href: "/products?origin=china&category=electronics",
      icon: "📱",
      gradient: "from-sky-500/20 to-zinc-100",
    },
    {
      id: "col-beauty",
      name: "Beauty",
      slug: "beauty",
      description: "Skincare and personal care",
      href: "/buy-from-tz",
      icon: "💄",
      gradient: "from-rose-400/20 to-zinc-100",
    },
    {
      id: "col-fashion",
      name: "Fashion",
      slug: "fashion",
      description: "Apparel and accessories",
      href: "/products?search=fashion",
      icon: "👗",
      gradient: "from-violet-400/20 to-zinc-100",
    },
    {
      id: "col-kitchen",
      name: "Kitchen",
      slug: "kitchen",
      description: "Home and cooking essentials",
      href: "/products?search=kitchen",
      icon: "🍽️",
      gradient: "from-amber-400/20 to-zinc-100",
    },
    {
      id: "col-kids",
      name: "Kids",
      slug: "kids",
      description: "Toys, care, and school",
      href: "/products?search=kids",
      icon: "🧸",
      gradient: "from-emerald-400/20 to-zinc-100",
    },
    {
      id: "col-office",
      name: "Office",
      slug: "office",
      description: "Work and study gear",
      href: "/products?search=office",
      icon: "💼",
      gradient: "from-blue-400/20 to-zinc-100",
    },
  ],
  whyChooseUs: [
    {
      id: "why-import",
      title: "Import Directly",
      description: "Source carefully selected products from China with clear import journeys.",
      icon: "import",
    },
    {
      id: "why-delivery",
      title: "Fast Delivery",
      description: "Air, sea, and local fulfillment options matched to each commerce journey.",
      icon: "delivery",
    },
    {
      id: "why-secure",
      title: "Secure Payments",
      description: "Checkout with trusted banks, cards, and mobile money partners.",
      icon: "secure",
    },
    {
      id: "why-quality",
      title: "Carefully Selected Products",
      description: "Curated catalog across China imports and Tanzanian storefronts.",
      icon: "quality",
    },
    {
      id: "why-support",
      title: "Customer Support",
      description: "Help when you need it — orders, delivery, and store questions.",
      icon: "support",
    },
  ],
  trustIndicators: [
    { id: "trust-secure", title: "Secure Checkout", description: "Protected payments on every order.", icon: "secure" },
    { id: "trust-delivery", title: "Reliable Delivery", description: "Tracked fulfillment to Tanzania.", icon: "delivery" },
    { id: "trust-support", title: "Customer Support", description: "Real help for real shoppers.", icon: "support" },
    { id: "trust-returns", title: "Return Policy", description: "Clear policies for eligible items.", icon: "returns" },
    { id: "trust-official", title: "Official Store", description: "Platform-operated storefront experience.", icon: "official" },
    { id: "trust-quality", title: "Quality Checked", description: "Catalog curation before publish.", icon: "quality" },
  ],
  trendingSearches: ["iPhone", "Kitchen", "Shoes", "Wigs", "Laptop"],
  newsletter: {
    title: "Stay Updated",
    description: "Receive offers and promotions.",
    placeholder: "Enter your email",
    ctaLabel: "Subscribe",
    successTitle: "You're subscribed!",
    successDescription: "Watch your inbox for offers from CHINA ORDER TZ.",
  },
  sections: {
    flashDeals: {
      eyebrow: "Limited time",
      title: "Flash Deals",
      description: "Time-sensitive prices across China imports and TZ stores.",
      viewAllLabel: "View all deals",
      viewAllHref: "/products",
    },
    newArrivals: {
      eyebrow: "Just in",
      title: "New Arrivals",
      description: "Newest products — separated by Order from China and Buy from TZ.",
      viewAllLabel: "Shop new",
      viewAllHref: "/products",
    },
    bestSellers: {
      eyebrow: "Customer favorites",
      title: "Best Sellers",
      description: "Most purchased and highest-rated products on the platform.",
      viewAllLabel: "View bestsellers",
      viewAllHref: "/products",
    },
    collections: {
      eyebrow: "Browse",
      title: "Featured Collections",
      description: "Shop by popular categories across both commerce journeys.",
      viewAllLabel: "All categories",
      viewAllHref: "/categories",
    },
    shopByStore: {
      eyebrow: "Buy from TZ",
      title: "Shop by Store",
      description: "Trusted Tanzanian storefronts — logos, banners, and local catalogs.",
      viewAllLabel: "All stores",
      viewAllHref: "/buy-from-tz",
    },
    sponsors: {
      eyebrow: "Partners",
      title: "Trusted Partners",
      description: "Banks, cards, and brands that advertise with CHINA ORDER TZ.",
    },
    whyChooseUs: {
      eyebrow: "The CHINA ORDER TZ difference",
      title: "Why Choose Us",
      description: "A commercial platform built for importing from China and shopping locally.",
    },
    trust: {
      eyebrow: "Platform trust",
      title: "Shop with Confidence",
      description: "What CHINA ORDER TZ stands for — not supplier verification claims.",
    },
  },
};
